# Generated by Django 5.0.6 on 2024-06-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
