# Generated by Django 5.1.3 on 2024-11-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_stock_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='data',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ticker',
        ),
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
