# Generated by Django 5.1.3 on 2024-12-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_stock_data_remove_stock_ticker_stock_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='images')),
                ('indexs', models.IntegerField(default=0)),
            ],
        ),
    ]
